#include "SoftwareSerial.h"
#include "DFPlayerMini_Fast.h"

static const uint8_t PIN_MP3_TX = 2; // Connects to module's RX
static const uint8_t PIN_MP3_RX = 3; // Connects to module's TX
SoftwareSerial softwareSerial(PIN_MP3_RX, PIN_MP3_TX);

DFPlayerMini_Fast player;

bool in1 = true;
bool in2 = true;
bool in3 = true;
bool in4 = true;
bool in5 = true;
bool in6 = true;
bool in7 = true;
bool in8 = true;
bool in9 = true;
bool in10 = true;
bool in11 = true;
bool in12 = true;

int l12;
int l11;
int l10;
int l9;
int l8;
int l7;
int l6 ;
int l5 ;
int l4 ;
int l3 ;
int l2 ;
int l1 ;

int l1in;
int l2in;
int l3in;
int l4in;
int l5in;
int l6in;
int l7in;
int l8in;
int l9in;
int l10in;
int l11in;
int l12in;

int c;
int ch;
int d;
int dh;
int e;
int f;
int fh;
int g;
int gh;
int a;
int ah;
int b;

int mode = 0;
int lastmode = 1;
int vol = 100;

int conf = 1;

void setup() {
  Serial.begin(9600);
  softwareSerial.begin(9600);

  pinMode(4,INPUT);
  pinMode(5,INPUT);
  pinMode(6,INPUT);
  pinMode(7,INPUT);
  pinMode(8,INPUT);
  pinMode(9,INPUT);
  pinMode(10,INPUT);
  pinMode(11,INPUT);
  pinMode(12,INPUT);
  pinMode(13,INPUT);
  pinMode(14,INPUT);
  pinMode(15,INPUT);

  if (player.begin(softwareSerial)) {
    Serial.println("OK");

    player.volume(25);

  }
  else {
    Serial.println("Connecting to DFPlayer Mini failed!");
  }
}

void loop() {

  l1 = digitalRead(15);
  l2 = digitalRead(14);
  l3 = digitalRead(13);
  l4 = digitalRead(12);
  l5 = digitalRead(11);
  l6 = digitalRead(10);
  l7 = digitalRead(9);
  l8 = digitalRead(8);
  l9 = digitalRead(7);
  l10 = digitalRead(6);
  l11 = digitalRead(5);
  l12 = digitalRead(4);
  
  
  if (Serial.available() > 0) {
    int a = Serial.read();
    if(a>=100){
      mode = a-100;
      // Serial.print("mode = ");
      // Serial.println(mode);
      Serial.write(1);
    }
    else if(a<100){
      vol = a;
      if(vol>30){
        vol = 30;
      }
      if(vol<0){
        vol = 0;
      }
      player.volume(vol);
      // Serial.print("vol = ");
      // Serial.println(vol);
      Serial.write(1);
    }
  }

  if(bool debug = false){ //Serial Print
    Serial.print(l12);
    Serial.print("  :  ");
    Serial.print(l11);
    Serial.print("  :  ");
    Serial.print(l10);
    Serial.print("  :  ");
    Serial.print(l9);
    Serial.print("  :  ");
    Serial.print(l8);
    Serial.print("  :  ");
    Serial.print(l7);
    Serial.print("  :  ");
    Serial.print(l6);
    Serial.print("  :  ");
    Serial.print(l5);
    Serial.print("  :  ");
    Serial.print(l4);
    Serial.print("  :  ");
    Serial.print(l3);
    Serial.print("  :  ");
    Serial.print(l2);
    Serial.print("  :  ");
    Serial.println(l1);
    }

  // File configuration:
  //   Concert piano Files : 0001-0012
  //   Amped Guitar 1 Files : 0013-0024
  //   Amped Guitar 2 Files : 0025-0036
  //   Ballad Grand Piano Files : 0037-0048
  //   Celtic Harp : 0049-0060
  //   Cinematic Piano : 0061-0072
  //   Concert Harp : 0073-0084
  //   Dreamy Rhodes : 0085-0096
  //   Just Arcade : 0097-0108
  //   Mariachi Trumpet 1 : 0109-0120
  //   Nostalgia : 0121-0132
  //   Steeldrum : 0132-0146
  if(mode != lastmode){
    if(mode == 12){
      conf = 1;
    }
    if(mode == 13){
      conf = 2;
    }

    if(conf == 1){
      c = 1 + (12*mode);
      ch = 2 + (12*mode);
      d = 3 + (12*mode);
      dh = 4 + (12*mode);
      e = 5 + (12*mode);
      f = 6 + (12*mode);
      fh = 7 + (12*mode);
      g = 8 + (12*mode);
      gh = 9 + (12*mode);
      a = 10 + (12*mode);
      ah = 11 + (12*mode);
      b = 12 + (12*mode);
      player.play(c);
      delay(100);
      }

    if(conf == 2){
      if(mode == 0){//Twinkle Twinkle
          player.play(c);
          delay(500);
          player.play(c);
          delay(500);
          player.play(g);
          delay(500);
          player.play(g);
          delay(500);
          player.play(a);
          delay(500);
          player.play(a);
          delay(500);
          player.play(g);
          delay(1000);
          player.play(f);
          delay(500);
          player.play(f);
          delay(500);
          player.play(e);
          delay(500);
          player.play(e);
          delay(500);
          player.play(d);
          delay(500);
          player.play(d);
          delay(500);
          player.play(c);
          delay(1000);

          
          player.play(g);
          delay(700);
          player.play(g);
          delay(250);
          player.play(f);
          delay(500);
          player.play(f);
          delay(500);
          player.play(e);
          delay(500);
          player.play(e);
          delay(500);
          player.play(d);
          delay(1000);
          
          player.play(g);
          delay(700);
          player.play(g);
          delay(250);
          player.play(f);
          delay(500);
          player.play(f);
          delay(500);
          player.play(e);
          delay(500);
          player.play(e);
          delay(500);
          player.play(d);
          delay(1000);
          
          player.play(c);
          delay(500);
          player.play(c);
          delay(500);
          player.play(g);
          delay(500);
          player.play(g);
          delay(500);
          player.play(a);
          delay(500);
          player.play(a);
          delay(500);
          player.play(g);
          delay(1000);
          player.play(f);
          delay(500);
          player.play(f);
          delay(500);
          player.play(e);
          delay(500);
          player.play(e);
          delay(500);
          player.play(d);
          delay(500);
          player.play(d);
          delay(500);
          player.play(c);
          delay(1000);
          }
      if(mode == 1){//Tetris
        player.play(g);
        delay(400);
        player.play(d);
        delay(200);
        player.play(dh);
        delay(200);
        player.play(f);
        delay(400);
        player.play(dh);
        delay(200);
        player.play(d);
        delay(200);
        player.play(c);
        delay(400);
        player.play(c);
        delay(200);
        player.play(dh);
        delay(200);
        player.play(g);
        delay(400);
        player.play(f);
        delay(200);
        player.play(dh);
        delay(200);
        player.play(d);
        delay(600);
        player.play(dh);
        delay(200);

        
        player.play(f);
        delay(400);
        player.play(g);
        delay(400);
        player.play(dh);
        delay(400);
        player.play(c);
        delay(400);
        player.play(c);
        delay(1000);
        player.play(f);
        delay(400);
        player.play(gh);
        delay(200);
        
        player.play(b);
        delay(400);
        player.play(ah);
        delay(200);
        player.play(gh);
        delay(200);
        player.play(g);
        delay(600);
        player.play(dh);
        delay(200);
        player.play(g);
        delay(400);
        player.play(f);
        delay(200);
        
        player.play(dh);
        delay(200);
        player.play(d);
        delay(400);
        player.play(d);
        delay(200);
        player.play(dh);
        delay(200);
        player.play(f);
        delay(400);
        player.play(g);
        delay(400);
        player.play(dh);
        delay(400);
        player.play(c);
        delay(400);
        player.play(c);
        delay(800);
        player.play(g);
        delay(400);
        player.play(d);
        delay(200);
        player.play(dh);
        delay(200);
        player.play(f);
        delay(400);
        player.play(dh);
        delay(200);
        player.play(d);
        delay(200);
        player.play(c);
        delay(400);
        player.play(c);
        delay(200);
        player.play(dh);
        delay(200);
        player.play(g);
        delay(400);
        player.play(f);
        delay(200);
        player.play(dh);
        delay(200);
        player.play(d);
        delay(600);
        player.play(dh);
        delay(200);

        
        player.play(f);
        delay(400);
        player.play(g);
        delay(400);
        player.play(dh);
        delay(400);
        player.play(c);
        delay(400);
        player.play(c);
        delay(1000);
        player.play(f);
        delay(400);
        player.play(gh);
        delay(200);
        
        player.play(b);
        delay(400);
        player.play(ah);
        delay(200);
        player.play(gh);
        delay(200);
        player.play(g);
        delay(600);
        player.play(dh);
        delay(200);
        player.play(g);
        delay(400);
        player.play(f);
        delay(200);
        
        player.play(dh);
        delay(200);
        player.play(d);
        delay(400);
        player.play(d);
        delay(200);
        player.play(dh);
        delay(200);
        player.play(f);
        delay(400);
        player.play(g);
        delay(400);
        player.play(dh);
        delay(400);
        player.play(c);
        delay(400);
        player.play(c);
        delay(800);
        player.play(g);
        delay(800);
        player.play(dh);
        delay(800);
        player.play(f);
        delay(800);
        player.play(d);
        delay(800);
        player.play(dh);
        delay(800);
        player.play(c);
        delay(800);
        player.play(b);
        delay(800);
        player.play(d);
        delay(800);
        player.play(g);
        delay(800);
        player.play(dh);
        delay(800);
        player.play(f);
        delay(800);
        player.play(d);
        delay(800);
        player.play(dh);
        delay(400);
        player.play(g);
        delay(400);
        player.play(c);
        delay(400);
        player.play(b);
        delay(800);

        player.stop();
          }
      if(mode == 2){//Jocelyn Flores    
        player.play(ch);
        delay(420);
        player.play(dh);
        delay(420);
        player.play(e);
        delay(420);
        player.play(b);
        delay(840);
        player.play(gh);
        delay(840);
        player.play(b);
        delay(840);
        player.play(dh);
        delay(2520);
        player.play(dh);
        delay(420);
        player.play(ch);
        delay(420);
        player.play(dh);
        delay(420);
        player.play(e);
        delay(420);
        player.play(b);
        delay(840);
        player.play(b);
        delay(840);
        player.play(gh);
        delay(840);

        
        player.play(b);
        delay(840);
        player.play(fh);
        delay(420);
        player.play(dh);
        delay(840);
        player.play(gh);
        delay(210);
        player.play(fh);
        delay(210);
        player.play(e);
        delay(210);
        player.play(dh);
        delay(210);
        
        player.play(ch);
        delay(420);
        player.play(dh);
        delay(420);
        player.play(e);
        delay(420);
        player.play(b);
        delay(840);
        player.play(gh);
        delay(840);
        player.play(b);
        delay(840);
        player.play(dh);
        delay(2520);
        
        player.play(dh);
        delay(420);
        player.play(ch);
        delay(420);
        player.play(dh);
        delay(420);
        player.play(e);
        delay(420);
        player.play(b);
        delay(840);
        player.play(b);
        delay(840);
        player.play(gh);
        delay(840);
        player.play(b);
        delay(840);
        player.play(ch);
        delay(420);
        player.play(dh);
        delay(840);
        player.play(gh);
        delay(210);
        player.play(fh);
        delay(210);
        player.play(e);
        delay(210);
        player.play(dh);
        delay(210);
        player.play(ch);
        delay(420);
        player.play(dh);
        delay(420);
        player.play(e);
        delay(420);
        player.play(b);
        delay(840);
        player.play(gh);
        delay(840);
        player.play(b);
        delay(840);
        player.play(dh);
        delay(2520);
        player.play(dh);
        delay(420);
        player.play(ch);
        delay(420);
        player.play(dh);
        delay(420);
        player.play(e);
        delay(420);
        player.play(b);
        delay(840);
        player.play(b);
        delay(840);
        player.play(gh);
        delay(840);

        
        player.play(b);
        delay(840);
        player.play(e);
        delay(420);
        player.play(dh);
        delay(840);
        player.play(gh);
        delay(210);
        player.play(fh);
        delay(210);
        player.play(e);
        delay(210);
        player.play(dh);
        delay(210);
        
        player.play(ch);
        delay(420);
        player.play(dh);
        delay(420);
        player.play(e);
        delay(420);
        player.play(b);
        delay(840);
        player.play(gh);
        delay(840);
        player.play(b);
        delay(840);
        player.play(dh);
        delay(2520);
        
        player.play(dh);
        delay(420);
        player.play(ch);
        delay(420);
        player.play(dh);
        delay(420);
        player.play(e);
        delay(420);
        player.play(b);
        delay(840);
        player.play(b);
        delay(840);
        player.play(gh);
        delay(840);
        player.play(b);
        delay(840);
        player.play(ch);
        delay(420);
        player.play(dh);
        delay(840);
        player.play(dh);
        delay(210);
        player.play(e);
        delay(210);
        player.play(fh);
        delay(210);
        player.play(gh);
        delay(210);

        player.stop();
        }
      if(mode == 3){//Golden Hour
          player.play(dh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(e);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(e);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(e);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(e);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);    
          player.play(ch);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(dh);
          delay(150);        
          player.play(c);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(c);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(c);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(ch);
          delay(450);
          player.play(f);
          delay(300);
          player.play(gh);
          delay(300);
          player.play(ah);
          delay(1200);
          player.play(ah);
          delay(300);
          player.play(c);
          delay(150);
          player.play(ch);
          delay(1350);    
          player.play(ah);
          delay(300);
          player.play(ch);
          delay(300);
          player.play(c);
          delay(300);
          player.play(ah);
          delay(300);
          player.play(gh);
          delay(300);
          player.play(gh);
          delay(600);
          player.play(f);
          delay(300);
          player.play(c);
          delay(300);
          player.play(ah);
          delay(300);
          player.play(gh);
          delay(300);
          player.play(c);
          delay(300);
          player.play(ah);
          delay(300);    
          player.play(gh);
          delay(300);    
          player.play(gh);
          delay(150);
          player.play(fh);
          delay(2250);
          player.play(ch);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(gh);
          delay(300);
          player.play(fh);
          delay(300);
          player.play(f);
          delay(300);
          player.play(f);
          delay(900);
          player.play(ah);
          delay(900);
          player.play(ch);
          delay(900);
          player.play(dh);
          delay(900);
          player.play(f);
          delay(3600);    
          player.play(ah);
          delay(900);  
          player.play(c);
          delay(900);
          player.play(gh);
          delay(900);
          player.play(fh);
          delay(900);
          player.play(f);
          delay(4500);
          player.play(c);
          delay(900);
          player.play(ch);
          delay(900);    
          player.play(dh);
          delay(900);  
          player.play(dh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(e);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(e);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(e);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(e);
          delay(150);
          player.play(f);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(ah);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(f);
          delay(150);    
          player.play(ch);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(gh);
          delay(150);
          player.play(fh);
          delay(150);
          player.play(dh);
          delay(150);        
          player.play(c);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(c);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(c);
          delay(150);
          player.play(ch);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(f);
          delay(150);
          player.play(dh);
          delay(150);
          player.play(ch);
          delay(450);

          player.stop();
        }
      if(mode == 4){//After Dark
        player.play(c);
        delay(410);
        player.play(c);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(c);
        delay(410);
        player.play(c);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(e);
        delay(410);
        player.play(e);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(e);
        delay(410);
        player.play(e);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(200);
        player.play(a);
        delay(200);
        player.play(c);
        delay(410);
        player.play(c);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(c);
        delay(410);
        player.play(c);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(e);
        delay(410);
        player.play(e);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(e);
        delay(410);
        player.play(e);
        delay(200);
        player.play(d);
        delay(410);
        player.play(d);
        delay(200);
        player.play(c);
        delay(200);
        player.play(b);
        delay(620);
        player.play(g);
        delay(200);
        player.play(a);
        delay(410);
        player.play(b);
        delay(1300);
        player.play(g);
        delay(200);
        player.play(a);
        delay(410);
        player.play(b);
        delay(1300);
        player.play(g);
        delay(200);
        player.play(a);
        delay(410);
        player.play(b);
        delay(1300);
        player.play(g);
        delay(200);
        player.play(a);
        delay(410);
        player.play(b);
        delay(1300);
        player.play(g);
        delay(200);
        player.play(a);
        delay(410);
        player.play(b);
        delay(1300);
        player.play(g);
        delay(200);
        player.play(a);
        delay(410);
        player.play(b);
        delay(1300);
        player.play(g);
        delay(200);        
        player.play(a);
        delay(410);
        player.play(b);
        delay(1300);
        player.play(g);
        delay(200);
        player.play(c);
        delay(410);
        player.play(b);
        delay(620);
        player.play(c);
        delay(410);
        player.play(c);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(c);
        delay(410);
        player.play(c);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(e);
        delay(410);
        player.play(e);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(e);
        delay(410);
        player.play(e);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(200);
        player.play(a);
        delay(200);
        player.play(c);
        delay(410);
        player.play(c);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(c);
        delay(410);
        player.play(c);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(e);
        delay(410);
        player.play(e);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(e);
        delay(410);
        player.play(e);
        delay(200);
        player.play(d);
        delay(410);
        player.play(d);
        delay(200);
        player.play(c);
        delay(200);
        player.play(b);
        delay(200);
        player.play(c);
        delay(410);
        player.play(c);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(c);
        delay(410);
        player.play(c);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(e);
        delay(410);
        player.play(e);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(e);
        delay(410);
        player.play(e);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(200);
        player.play(a);
        delay(200);
        player.play(c);
        delay(410);
        player.play(c);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(c);
        delay(410);
        player.play(c);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(e);
        delay(410);
        player.play(e);
        delay(200);
        player.play(b);
        delay(410);
        player.play(b);
        delay(200);
        player.play(g);
        delay(410);
        player.play(e);
        delay(410);
        player.play(e);
        delay(200);
        player.play(d);
        delay(410);
        player.play(d);
        delay(200);
        player.play(c);
        delay(820);

        player.stop();
        }
      if(mode == 5){//Under The Influence
        player.play(a);
        delay(400);
        player.play(a);
        delay(400);
        player.play(g);
        delay(1350);
        player.play(e);
        delay(400);
        player.play(e);
        delay(400);
        player.play(d);
        delay(270);
        player.play(d);
        delay(1080);
        player.play(a);
        delay(400);
        player.play(a);
        delay(400);
        player.play(g);
        delay(1350);
        player.play(e);
        delay(400);
        player.play(e);
        delay(400);
        player.play(d);
        delay(270);
        player.play(e);
        delay(540);
        player.play(e);
        delay(270);
        player.play(g);
        delay(270);
        player.play(a);
        delay(400);
        player.play(a);
        delay(400);
        player.play(g);
        delay(1350);
        player.play(e);
        delay(400);
        player.play(e);
        delay(400);
        player.play(d);
        delay(270);
        player.play(d);
        delay(1080);
        player.play(a);
        delay(400);
        player.play(a);
        delay(400);
        player.play(g);
        delay(270);
        player.play(g);
        delay(540);
        player.play(e);
        delay(270);
        player.play(d);
        delay(540);
        player.play(e);
        delay(1890);
        player.play(c);
        delay(270);
        player.play(c);
        delay(270);
        player.play(c);
        delay(270);
        player.play(a);
        delay(270);
        player.play(b);
        delay(540);
        player.play(b);
        delay(1350);
        player.play(a);
        delay(270);
        player.play(a);
        delay(270);
        player.play(a);
        delay(270);
        player.play(c);
        delay(270);
        player.play(a);
        delay(270);
        player.play(c);
        delay(540);
        player.play(c);
        delay(270);
        player.play(a);
        delay(270);
        player.play(b);
        delay(540);
        player.play(b);
        delay(540);
        player.play(a);
        delay(270);
        player.play(g);
        delay(270);
        player.play(g);
        delay(540);
        player.play(a);
        delay(540);
        player.play(a);
        delay(270);
        player.play(a);
        delay(270);
        player.play(a);
        delay(270);
        player.play(c);
        delay(270);
        player.play(c);
        delay(270);
        player.play(a);
        delay(270);
        player.play(b);
        delay(540);
        player.play(b);
        delay(540);
        player.play(g);
        delay(270);
        player.play(a);
        delay(270);
        player.play(a);
        delay(540);        
        player.play(a);
        delay(540);
        player.play(a);
        delay(270);
        player.play(a);
        delay(270);
        player.play(e);
        delay(540);
        player.play(a);
        delay(540);
        player.play(g);
        delay(540);
        player.play(a);
        delay(270);
        player.play(a);
        delay(270);
        player.play(e);
        delay(540);
        player.play(a);
        delay(540);
        player.play(g);
        delay(1080);
        player.play(c);
        delay(270);
        player.play(c);
        delay(270);
        player.play(c);
        delay(270);
        player.play(a);
        delay(270);
        player.play(a);
        delay(270);
        player.play(b);
        delay(270);
        player.play(b);
        delay(810);
        player.play(a);
        delay(270);
        player.play(a);
        delay(270);
        player.play(b);
        delay(270);
        player.play(a);
        delay(540);
        player.play(a);
        delay(270);
        player.play(a);
        delay(270);
        player.play(e);
        delay(540);
        player.play(a);
        delay(540);
        player.play(g);
        delay(540);
        player.play(a);
        delay(270);
        player.play(a);
        delay(270);
        player.play(e);
        delay(540);
        player.play(a);
        delay(540);
        player.play(g);
        delay(1080);
        player.play(c);
        delay(270);
        player.play(c);
        delay(270);
        player.play(c);
        delay(270);
        player.play(c);
        delay(270);
        player.play(c);
        delay(270);
        player.play(d);
        delay(270);
        player.play(d);
        delay(810);
        player.play(c);
        delay(270);
        player.play(c);
        delay(270);
        player.play(d);
        delay(270);
        player.play(c);
        delay(270);
        player.play(b);
        delay(270);
        player.play(a);
        delay(1080);
        player.play(e);
        delay(540);
        player.play(b);
        delay(270);
        player.play(b);
        delay(1080);
        player.play(a);
        delay(270);
        player.play(c);
        delay(270);
        player.play(a);
        delay(270);
        player.play(c);
        delay(540);
        player.play(c);
        delay(1080);
        player.play(e);
        delay(540);
        player.play(b);
        delay(270);
        player.play(b);
        delay(2430);
        player.play(a);
        delay(400);
        player.play(a);
        delay(400);
        player.play(g);
        delay(270);
        player.play(g);
        delay(1350);
        player.play(e);
        delay(400);
        player.play(e);
        delay(400);
        player.play(d);
        delay(270);
        player.play(d);
        delay(1080);
        player.play(a);
        delay(400);
        player.play(a);
        delay(400);
        player.play(g);
        delay(270);
        player.play(g);
        delay(1350);
        player.play(e);
        delay(400);
        player.play(e);
        delay(400);
        player.play(d);
        delay(270);
        player.play(e);
        delay(540);
        player.play(e);
        delay(270);
        player.play(g);
        delay(270);
        player.play(a);
        delay(400);
        player.play(a);
        delay(400);
        player.play(g);
        delay(270);
        player.play(g);
        delay(1350);
        player.play(e);
        delay(400);
        player.play(e);
        delay(400);
        player.play(d);
        delay(270);
        player.play(d);
        delay(1080);
        player.play(a);
        delay(400);
        player.play(a);
        delay(400);
        player.play(g);
        delay(270);
        player.play(g);
        delay(540);
        player.play(e);
        delay(270);
        player.play(d);
        delay(540);
        player.play(e);
        delay(2430);

        player.stop();
       }
      if(mode == 6){//Aadat
        player.play(g);
        delay(370);
        player.play(gh);
        delay(180);
        player.play(g);
        delay(180);
        player.play(g);
        delay(560);
        player.play(g);
        delay(560);
        player.play(g);
        delay(370);
        player.play(g);
        delay(370);
        player.play(f);
        delay(370);
        player.play(dh);
        delay(370);
        player.play(d);
        delay(370);
        player.play(d);
        delay(370);
        player.play(f);
        delay(740);
        player.play(f);
        delay(370);
        player.play(d);
        delay(740);
        player.play(dh);
        delay(370);
        player.play(d);
        delay(370);
        player.play(c);
        delay(560);
        player.play(dh);
        delay(560);
        player.play(dh);
        delay(1480);
        player.play(f);
        delay(180);
        player.play(dh);
        delay(180);
        player.play(d);
        delay(1110);
        player.play(d);
        delay(1110);
        player.play(g);
        delay(370);
        player.play(gh);
        delay(180);
        player.play(g);
        delay(180);
        player.play(g);
        delay(560);
        player.play(g);
        delay(560);
        player.play(gh);
        delay(740);
        player.play(ah);
        delay(370);
        player.play(c);
        delay(370);
        player.play(ah);
        delay(370);
        player.play(c);
        delay(180);
        player.play(d);
        delay(180);
        player.play(c);
        delay(180);
        player.play(ah);
        delay(560);
        player.play(ah);
        delay(370);
        player.play(ah);
        delay(740);
        player.play(gh);
        delay(740);
        player.play(gh);
        delay(180);
        player.play(ah);
        delay(180);
        player.play(gh);
        delay(180);
        player.play(g);
        delay(1680);
        player.play(g);
        delay(370);
        player.play(gh);
        delay(180);
        player.play(g);
        delay(180);
        player.play(f);
        delay(2240);
        player.play(g);
        delay(370);
        player.play(gh);
        delay(180);
        player.play(g);
        delay(180);
        player.play(g);
        delay(560);
        player.play(g);
        delay(560);
        player.play(g);
        delay(370);
        player.play(g);
        delay(370);
        player.play(f);
        delay(370);
        player.play(dh);
        delay(370);
        player.play(d);
        delay(370);
        player.play(d);
        delay(370);
        player.play(f);
        delay(740);
        player.play(f);
        delay(370);
        player.play(d);
        delay(740);
        player.play(dh);
        delay(370);
        player.play(d);
        delay(370);
        player.play(c);
        delay(560);
        player.play(dh);
        delay(560);
        player.play(dh);
        delay(1480);
        player.play(f);
        delay(180);
        player.play(dh);
        delay(180);
        player.play(d);
        delay(1110);
        player.play(d);
        delay(1110);
        player.play(g);
        delay(370);
        player.play(gh);
        delay(180);
        player.play(g);
        delay(180);
        player.play(g);
        delay(560);
        player.play(g);
        delay(560);
        player.play(gh);
        delay(740);
        player.play(ah);
        delay(370);
        player.play(c);
        delay(370);
        player.play(ah);
        delay(370);
        player.play(c);
        delay(180);
        player.play(d);
        delay(180);
        player.play(c);
        delay(180);
        player.play(ah);
        delay(560);
        player.play(ah);
        delay(370);
        player.play(ah);
        delay(370);
        player.play(ah);
        delay(370);
        player.play(gh);
        delay(740);
        player.play(gh);
        delay(180);
        player.play(ah);
        delay(180);
        player.play(gh);
        delay(180);
        player.play(g);
        delay(1680);
        player.play(g);
        delay(370);
        player.play(gh);
        delay(180);
        player.play(g);
        delay(180);
        player.play(f);
        delay(1110);
        player.play(c);
        delay(370);
        player.play(d);
        delay(740);
        player.play(d);
        delay(740);
        player.play(d);
        delay(370);
        player.play(dh);
        delay(370);
        player.play(d);
        delay(370);
        player.play(dh);
        delay(1480);
        player.play(g);
        delay(180);
        player.play(f);
        delay(180);
        player.play(d);
        delay(370);
        player.play(dh);
        delay(370);
        player.play(d);
        delay(370);
        player.play(dh);
        delay(1850);
        player.play(dh);
        delay(370);        
        player.play(f);
        delay(370);
        player.play(dh);
        delay(370);
        player.play(f);
        delay(1480);
        player.play(f);
        delay(180);
        player.play(dh);
        delay(180);
        player.play(d);
        delay(2220);
        player.play(d);
        delay(740);
        player.play(dh);
        delay(180);
        player.play(d);
        delay(180);
        player.play(dh);
        delay(180);
        player.play(f);
        delay(180);
        player.play(dh);
        delay(180);
        player.play(d);
        delay(180);
        player.play(dh);
        delay(180);
        player.play(f);
        delay(180);
        player.play(dh);
        delay(180);
        player.play(d);
        delay(180);
        player.play(dh);
        delay(180);
        player.play(f);
        delay(180);
        player.play(dh);
        delay(740);
        player.play(dh);
        delay(180);
        player.play(d);
        delay(180);
        player.play(dh);
        delay(180);
        player.play(f);
        delay(180);
        player.play(dh);
        delay(180);
        player.play(d);
        delay(180);
        player.play(dh);
        delay(180);
        player.play(f);
        delay(180);
        player.play(dh);
        delay(180);
        player.play(d);
        delay(180);
        player.play(dh);
        delay(180);
        player.play(f);
        delay(180);
        player.play(dh);
        delay(740);
        player.play(dh);
        delay(370);
        player.play(f);
        delay(370);
        player.play(dh);
        delay(370);
        player.play(f);
        delay(1110);
        player.play(dh);
        delay(370);
        player.play(f);
        delay(180);
        player.play(dh);
        delay(180);
        player.play(d);
        delay(2220);
        
        player.stop();
        }
      }

        lastmode = mode;
    }

  // conf 1 == harp
  // conf 2 == songs

  // mode 12 == Twinkle Twinkle
  // mode 13 == Tetris
  // mode 14 == Jocelyn Flores

    harp(c,ch,d,dh,e,f,fh,g,gh,a,ah,b);
  if(false){ // Tetris
  
    player.play(g);
    delay(400);
    player.play(d);
    delay(200);
    player.play(dh);
    delay(200);
    player.play(f);
    delay(400);
    player.play(dh);
    delay(200);
    player.play(d);
    delay(200);
    player.play(c);
    delay(400);
    player.play(c);
    delay(200);
    player.play(dh);
    delay(200);
    player.play(g);
    delay(400);
    player.play(f);
    delay(200);
    player.play(dh);
    delay(200);
    player.play(d);
    delay(600);
    player.play(dh);
    delay(200);

    
    player.play(f);
    delay(400);
    player.play(g);
    delay(400);
    player.play(dh);
    delay(400);
    player.play(c);
    delay(400);
    player.play(c);
    delay(1000);
    player.play(f);
    delay(400);
    player.play(gh);
    delay(200);
    
    player.play(b);
    delay(400);
    player.play(ah);
    delay(200);
    player.play(gh);
    delay(200);
    player.play(g);
    delay(600);
    player.play(dh);
    delay(200);
    player.play(g);
    delay(400);
    player.play(f);
    delay(200);
    
    player.play(dh);
    delay(200);
    player.play(d);
    delay(400);
    player.play(d);
    delay(200);
    player.play(dh);
    delay(200);
    player.play(f);
    delay(400);
    player.play(g);
    delay(400);
    player.play(dh);
    delay(400);
    player.play(c);
    delay(400);
    player.play(c);
    delay(800);
  }
  // if(mode >= 12){
  //   mode = 0;
  //   lastmode = 0;
  // }
}
int harp(int one,int two, int three,int four,int five,int six,int seven,int eight,int nine,int ten,int eleven,int twelve){
  
  if(l1 == 1 && in1){
    player.play(one);
    in1 = false;
    }
  if(!in1 && l1 == 0){
    in1 = true;
  }
  //
  if(l2 == 1 && in2){
    player.play(two);
    in2 = false;
  }
  if(!in2 && l2 == 0){
    in2 = true;
  }
  //
  if(l3 == 1 && in3){
    player.play(three);
    in3 = false;
  }
  if(!in3 && l3 == 0){
    in3 = true;
  }
  //  
  if(l4 == 1 && in4){
    player.play(four);
    in4 = false;
  }
  if(!in4 && l4 == 0){
    in4 = true;
  }
  //
  if(l5 == 1 && in5){
    player.play(five);
    in5 = false;
  }
  if(!in5 && l5 == 0){
    in5 = true;
  }
  //  
  if(l6 == 1 && in6){
    player.play(six);
    in6 = false;
  }
  if(!in6 && l6 == 0){
    in6 = true;
  }
  //  
  if(l7 == 1 && in7){
    player.play(seven);
    in7 = false;
  }
  if(!in7 && l7 == 0){
    in7 = true;
  }
  // 
  if(l8 == 1 && in8){
    player.play(eight);
    in8 = false;
  }
  if(!in8 && l8 == 0){
    in8 = true;
  }
  //  
  if(l9 == 1 && in9){
    player.play(nine);
    in9 = false;
  }
  if(!in9 && l9 == 0){
    in9 = true;
  }
  //
  if(l10 == 1 && in10){
    player.play(ten);
    in10 = false;
  }
  if(!in10 && l10 == 0){
    in10 = true;
  }
  //
  if(l11 == 1 && in11){
    player.play(eleven);
    in11 = false;
  }
  if(!in11 && l11 == 0){
    in11 = true;
  }
  //  
  if(l12 == 1 && in12){
    player.play(twelve);
    in12 = false;
  }
  if(!in12 && l12 == 0){
    in12 = true;
  }
}
